### PR TITLE
Add support for splay, modulepath and symlinks

### PR DESCRIPTION
**Pull request by ajmaidak**
* Add support for adding splay to agent configuration
* Add support for removing modulepath form agent configuration
* Add support for not adding symlinks in /usr/bin
* Add fixtures.yml so tests can work
* Switch from simple string equality to versioncmp for upgrades

### CODE REVIEW

**Comment by aharden** [comment]
@ajmaidak These are all great additions; I haven't tested any of this yet.  I'm reviewing the splay setting here: https://docs.puppetlabs.com/references/latest/configuration.html#splay.  It looks like your code intends to set 'splay' to a value rather than to true or false.  To set a splay value, you have to set 'splay' to true and use the 'splaylimit' setting to override the default ($runinterval).  I can refactor what you gave me into a single parameter that manages both config settings and document it.  Do you want to refactor this and resubmit?  I'm OK with doing it.  I will probably get to this by Tuesday.

Thanks again!

**Comment by ajmaidak** [comment]
Yeah, splay should be a bool, I think was being lazy when I was working on this and just passed it through as a string.  I'll fix-up.

**Comment by ajmaidak** [comment]
@aharden I think this is what you were looking for... Let me know if I missed the mark.

I did not mess with "splaylimit"  at my site we've never needed to tamper with this.

**Comment by aharden** [comment]
@ajmaidak Definitely.  I will work all this into some other adjustments for a 1.2.0 release.  Thanks!

**Comment by ajmaidak** [comment]
Thanks!

**Pull request merged**
